export const allNewsItems = [
        { id: 'anbi-regelgeving-2029', tag: 'Regelgeving', date: '8 jul 2026', title: 'ANBI-regelgeving: kabinet kondigt bestedingsplicht en toezichtportals aan voor 2029-2030', excerpt: 'Voor de circa 45.000 Nederlandse ANBI\'s landen de belangrijkste wijzigingen niet volgend jaar, maar in de periode 2028-2030.', source: 'Kamerbrief stand van zaken verbetermogelijkheden ANBI-regeling (kenmerk 2026-0000138567), Ministerie van Financiën, 1 juni 2026; PwC Belastingnieuws; Taxence; Govers Accountants/Adviseurs.', body: [
          { h: '', paras: [`Staatssecretaris Eerenberg van Financiën informeerde de Tweede Kamer op 1 juni 2026 over de stand van zaken van de aangekondigde verbeteringen in de ANBI-regeling. De brief is een vervolg op de kabinetsreactie van 1 juli 2025 op de evaluatie van de ANBI- en SBBI-regelingen, en maakt een aantal eerder aangekondigde onderzoeken nu concreet. Voor de circa 45.000 Nederlandse ANBI's landen de belangrijkste wijzigingen niet volgend jaar, maar in de periode 2028-2030.`] },
          { h: 'De belangrijkste maatregel: bestedingsplicht per 2029', paras: [`Het kabinet is voornemens om per 1 januari 2029 een bestedingsverplichting in te voeren voor instellingen die hun ANBI-status verliezen. Het resterende ANBI-vermogen moet dan binnen twee jaar worden besteed aan het algemeen nut, of worden overgedragen aan een andere ANBI. Bij niet-naleving kan de Belastingdienst een bestuurlijke boete opleggen. Deze maatregel is een reactie op onderzoek waaruit bleek dat in de periode 2020-2023 jaarlijks tussen de 1.050 en 1.450 instellingen hun ANBI-status verloren, waarvan een deel het opgebouwde vermogen vervolgens niet meer aantoonbaar aan het algemeen nut besteedde. Een verdergaande optie, een fiscale eindheffing bij verlies van de ANBI-status, is onderzocht, maar wordt vanwege de complexiteit niet verder uitgewerkt.`] },
          { h: 'Twee digitale portals, twee jaartallen', paras: [`Voor beter toezicht werkt de Belastingdienst aan twee aparte portals, waarvoor in april 2025 al een wetsvoorstel is ingediend: een toezichtportal en een portal voor de publicatieplicht. Deze zijn niet gelijktijdig operationeel. De publicatieplicht-omgeving wordt naar verwachting vanaf 2029 in gebruik genomen, het centrale toezichtportal volgt naar verwachting rond 2030. Vooruitlopend daarop intensiveert de Belastingdienst het toezicht al eerder: het ANBI-team wordt in 2026 uitgebreid met acht fte aan breder opgeleide medewerkers.`] },
          { h: 'Giftenaftrek: evaluatie in 2028', paras: [`Een volgend natuurlijk beoordelingsmoment voor de giftenaftrek zelf ligt in 2028. Dan wordt geëvalueerd wat het effect is geweest van recente aanpassingen, waaronder de verhoging van het maximum voor periodieke giften naar € 1,5 miljoen per jaar sinds 2025. Het kabinet ziet er vooralsnog van af om de giftenaftrek te vervangen door een geefsubsidie: dat zou volgens de staatssecretaris tot meer administratieve lasten bij ontvangende instellingen leiden en lastiger uitvoerbaar zijn.`] },
          { h: 'Een tegemoetkoming voor de praktijk', paras: [`Niet alle nieuws is aanscherping. De Kamerbrief bevestigt ook een tegemoetkoming die in de praktijk vaak voorkomt bij internationaal werkende ANBI's: een ANBI mag financiële steun geven aan een organisatie zonder ANBI-status, mits aantoonbaar is dat de middelen in lijn met de eigen algemeen nuttige doelstelling worden besteed en de ANBI daar toezicht op houdt. Dat is relevant voor ANBI's die partner- of zusterorganisaties in het buitenland ondersteunen.`] },
          { h: 'Nog lopende onderzoeken', paras: [`Daarnaast lopen nog aparte onderzoeken naar ANBI's die betrokken zijn bij NSW-landgoederen (eerste resultaten verwacht in de tweede helft van 2026), naar constructies met familiestichtingen, en naar een mogelijke algehele belastingplicht voor stichtingen en verenigingen, waarover de staatssecretaris nog vóór de zomer apart bericht. Ook volgt nog een inhoudelijke reactie op het advies Beter Geven III over een alternatief voor de regeling 'geven uit de vennootschap'.`] },
          { h: 'Voor de praktijk', paras: [`Voor ANBI-besturen is er dus geen acute wetswijziging op til, maar wel een duidelijke richting: meer toezicht, meer digitalisering van de informatie-uitwisseling, en een harde verplichting om vermogen na het verlies van de ANBI-status daadwerkelijk te besteden. Instellingen die krimpen, fuseren of hun ANBI-status om andere redenen dreigen te verliezen, doen er goed aan om nu al na te denken over de bestemming van resterend vermogen, ruim voordat de verplichting in 2029 ingaat.`] }
        ] },
        { id: 'palliatieve-zorg-deadline', tag: 'Deadline', date: '30 jun 2026', title: 'Let op: aanvraagtermijn voor subsidie tot € 1,3 miljoen sluit over twee weken', excerpt: 'Instellingen die vrijwilligers inzetten in de palliatieve terminale zorg hebben nog tot en met 15 juli de tijd om subsidie aan te vragen bij DUS-I.', source: 'Dienst Uitvoering Subsidies aan Instellingen (DUS-I), Ministerie van Volksgezondheid, Welzijn en Sport, regeling Palliatieve terminale zorg en geestelijke verzorging thuis.', body: [
          { h: '', paras: [`Instellingen die vrijwilligers inzetten in de palliatieve terminale zorg hebben nog tot en met 15 juli, over twee weken, de tijd om subsidie aan te vragen bij Dienst Uitvoering Subsidies aan Instellingen (DUS-I). Wie hierover nadenkt, kan de aanvraag nu al voorbereiden.`] },
          { h: 'Waar gaat het om', paras: [`De regeling ondersteunt de inzet, opleiding en coördinatie van vrijwilligers die palliatieve terminale zorg verlenen, thuis, in een hospice of in een andere zorginstelling. De hoogte van de instellingssubsidie hangt af van het gemiddeld aantal cliënten dat de instelling in de referentieperiode heeft geholpen, maximaal drie jaar terugkijkend vanaf 31 december van het voorgaande kalenderjaar. Aanvragers zijn onder te verdelen in zes categorieën, van thuisorganisaties met onbetaalde coördinatie tot zelfstandige high care hospices, elk met een eigen normbedrag per cliënt.`] },
          { h: 'Waarom de datum er hard toe doet', paras: [`Het aanvraagvenster voor deze vrijwilligersstroom loopt van 26 mei tot en met 15 juli 2026. Instellingen die hun cliëntenaantallen en aanvraag nu nog niet compleet hebben, doen er goed aan om vandaag te controleren of de administratie op orde is: de referentieperiode, de juiste categorie-indeling en het ingevulde cliëntenformulier moeten kloppen voordat de aanvraag wordt ingediend. Wie deze deadline mist, is voor het lopende boekjaar aangewezen op een volgend aanvraagmoment.`] },
          { h: 'Twee sporen, twee data', paras: [`Deze regeling kent naast de vrijwilligersstroom ook een spoor voor regionale netwerken palliatieve zorg en voor instellingen die geestelijke verzorging aan huis bieden, daarvoor geldt een ander en later venster, van 1 tot en met 30 september 2026. Voor organisaties die beide onderdelen aanvragen is het dus zaak de twee data goed uit elkaar te houden: het ene loopt nu af, het andere begint pas na de zomer.`] },
          { h: 'Voor de praktijk', paras: [`De regeling is onlangs verlengd tot 1 januari 2028, met een evaluatie die dit jaar plaatsvindt. Dat betekent dat de huidige voorwaarden voorlopig blijven bestaan, maar ook dat de vorm van de subsidie na de evaluatie kan veranderen. Voor organisaties die structureel op deze financiering leunen, is het raadzaam de evaluatie te volgen zodra de resultaten bekend worden.`] }
        ] },
        { id: 'extra-budget-ontwikkelingssamenwerking', tag: 'Beleid', date: '26 jun 2026', title: 'Kabinet trekt alsnog 380 miljoen euro extra uit voor ontwikkelingssamenwerking', excerpt: 'Na jaren van bezuinigingen komt er onverwacht extra geld beschikbaar voor internationale samenwerking, door Partos gelezen als een eerste stap richting herstel.', source: 'Vakblad fondsenwerving, berichtgeving over kabinetsbesluit ontwikkelingssamenwerking.', body: [
          { h: '', paras: [`Na jaren van bezuinigingen komt er onverwacht extra geld beschikbaar voor internationale samenwerking. Het kabinet heeft besloten 380 miljoen euro extra vrij te maken voor ontwikkelingssamenwerking, een beslissing die door belangenbehartiger Partos wordt gelezen als een eerste stap richting herstel van het budget.`] },
          { h: 'Wat eraan voorafging', paras: [`De Nederlandse non-profitsector kreeg de afgelopen jaren te maken met stevige kortingen onder het kabinet Schoof, met name op de budgetten voor internationale samenwerking. Die bezuinigingen kwamen boven op andere druk waar de sector mee te maken had: onzekerheid over de giftenaftrek en toenemende regeldruk voor vrijwilligersorganisaties. Voor organisaties die afhankelijk zijn van dit type financiering betekende dat de afgelopen periode vooral onzekerheid over de omvang en continuïteit van hun budgetten.`] },
          { h: 'Hoe de extra investering tot stand kwam', paras: [`De extra 380 miljoen euro kwam er na steun van Progressief Nederland en de inzet van minister Sjoerdsma (D66, Buitenlandse Handel en Ontwikkelingssamenwerking). Partos ziet in de stap erkenning van het belang van internationale solidariteit en van de rol die maatschappelijke organisaties daarin spelen.`] },
          { h: 'Eén stap, geen trendbreuk', paras: [`Belangrijk om scherp te houden: Partos noemt dit zelf een eerste stap, niet een volledig herstel. Hoogleraar filantropie René Bekkers wijst er in het rapport Geven in Nederland 2026 op dat sommige van de onzekerheden rond het budget voor internationale samenwerking inmiddels zijn verholpen, maar dat andere in de eerste helft van 2026 nog altijd spelen. Voor organisaties die hierop plannen, betekent dit dat optimisme op zijn plaats is, maar dat meerjarige zekerheid nog niet is teruggekeerd.`] },
          { h: 'Wat dit betekent voor de praktijk', paras: [`Voor fondsenwervers en beleidsmedewerkers bij internationale organisaties is dit een moment om actuele beleidscommunicatie te volgen en waar relevant in gesprek te gaan met Partos en andere brancheorganisaties over hoe de extra middelen worden verdeeld. Voor kleinere organisaties die niet direct op rijksmiddelen leunen, blijft de combinatie van diverse financieringsbronnen, subsidie, vermogensfondsen en particuliere gevers, de meest solide basis, juist in een periode waarin overheidsbudgetten nog kunnen schuiven.`] }
        ] },
        { id: 'recordopbrengsten-evenementen', tag: 'Praktijk', date: '12 jun 2026', title: 'Recordopbrengsten laten zien wat georganiseerde fondsenwerving kan opleveren', excerpt: 'Meerdere grote fondsenwervende evenementen haalden indrukwekkende bedragen op, en laten alle drie een net iets ander recept zien.', source: 'Vakblad fondsenwerving, nieuwsberichtgeving over Tour du ALS, Nacht van de Vluchteling en Amsterdam Dinner 2026.', body: [
          { h: '', paras: [`Soms is het goed om de nuchtere cijfers even te laten voor wat ze zijn en te kijken naar wat er in de praktijk daadwerkelijk wordt binnengehaald. De afgelopen periode leverden meerdere grote fondsenwervende evenementen indrukwekkende bedragen op, en ze laten alle drie een net iets ander recept zien.`] },
          { h: 'Tour du ALS en Nacht van de Vluchteling: twee miljoen, twee keer', paras: [`In dezelfde week haalden Tour du ALS (voor ALS Nederland) en de Nacht van de Vluchteling (voor Stichting Vluchteling) beide ruim twee miljoen euro op. Twee volledig verschillende doelgroepen en twee verschillende soorten activiteiten, de een een sportief uithoudingsevenement, de ander een nachtelijke wandeltocht, maar met een gedeeld kenmerk: deelnemers werven zelf hun eigen netwerk aan sponsoren. Dat peer-to-peer-element is precies het mechanisme dat in vrijwel elke trendanalyse voor 2026 als groeimotor wordt genoemd: mensen geven eerder aan iemand die ze kennen dan aan een abstracte organisatie.`] },
          { h: 'Amsterdam Dinner: 32 jaar, nog altijd een recordbedrag', paras: [`Het jaarlijkse benefietdiner in AFAS Live, gehouden ten behoeve van de opsporing van hiv bij baby's en kinderen in Malawi, vierde dit jaar zijn 32e editie met het thema 'The Enchanted Forest' en noteerde een recordopbrengst. Onder de ruim duizend aanwezigen bevonden zich prominenten uit kunst, media, politiek, wetenschap en het bedrijfsleven, en de avond bracht bovendien een groot eerbetoon aan fotograaf Erwin Olaf. Dat een evenement na 32 jaar nog altijd een record kan neerzetten, is een signaal dat een sterk merk en een herkenbare traditie op de lange termijn blijven renderen, iets wat niet elk jaarlijks terugkerend evenement lukt.`] },
          { h: 'Wat deze drie voorbeelden gemeen hebben', paras: [`Ondanks de verschillen in schaal, doelgroep en opzet delen deze drie evenementen een paar terugkerende ingrediënten: een duidelijke, invoelbare aanleiding, een sterk netwerk van betrokkenen dat het verhaal zelf verder verspreidt, en jarenlange consistentie in uitvoering. Geen van de drie is een eenmalig succes; het zijn evenementen die hun positie over meerdere edities hebben opgebouwd.`] },
          { h: 'Voor de eigen praktijk', paras: [`Voor organisaties die een eigen wervend evenement overwegen, is de les niet dat groot per se beter is. De Nacht van de Vluchteling en Tour du ALS laten zien dat peer-to-peer-opzet ook zonder decennialange traditie tot miljoenenbedragen kan leiden, mits de doelgroep zich er persoonlijk bij betrokken voelt. Amsterdam Dinner laat zien wat er op de lange termijn mogelijk is wanneer een evenement uitgroeit tot een vaste waarde in de agenda van een trouwe kring gevers.`] }
        ] },
        { id: 'nalatenschappen-groeimarkt', tag: 'Vakkennis', date: '28 mei 2026', title: 'De stille groeimarkt: nalatenschappen in de Nederlandse fondsenwerving', excerpt: 'Terwijl de instroom van jonge donateurs onder druk staat, groeit de nalatenschap gestaag door, een van de weinige structureel groeiende inkomstenbronnen.', source: 'Geven in Nederland 2026 (Centrum voor Filantropische Studies); Legacy Monitor Netherlands (vijfde editie).', body: [
          { h: '', paras: [`Terwijl de instroom van nieuwe, jonge donateurs in veel organisaties onder druk staat, groeit er ergens anders iets gestaag door: de nalatenschap. Uit zowel Geven in Nederland 2026 als de vijfde editie van de Legacy Monitor Netherlands blijkt dat inkomsten uit erfenissen een van de weinige structureel groeiende inkomstenbronnen in de sector zijn.`] },
          { h: 'Cijfers die aandacht verdienen', paras: [`De opbrengst uit nalatenschappen steeg in het meest recente onderzoeksjaar met dertien procent, de grootste toename sinds de metingen begonnen. Initiatiefnemer Arjen van Ketel van de Legacy Monitor werkt al sinds 2001 aan de werving van nalatenschappen en wijst erop dat Nederland, na Groot-Brittannië, een van de weinige landen is met een jaarlijks benchmarkonderzoek op dit onderwerp. Dat zegt iets over het belang dat de sector er zelf al aan hecht.`] },
          { h: 'Waarom dit geen kortetermijnstrategie is', paras: [`Nalatenschapswerving werkt anders dan de meeste andere vormen van fondsenwerving. De relatie met een potentiële nalater bouwt zich op over jaren, soms decennia, en vraagt om een andere toon dan een wervingscampagne: minder gericht op directe conversie, meer op vertrouwen en continuïteit. Tijdens de Vakdag fondsenwerving 2026 is dit thema dan ook nadrukkelijk geagendeerd, met een sessie specifiek gewijd aan het investeren in de relatie met potentiële nalaters.`] },
          { h: 'De verbinding met de rest van het fondsenwervingsprogramma', paras: [`Organisaties die succesvol zijn in nalatenschapswerving, behandelen het zelden als een geïsoleerd programma. Het loopt mee in de bredere donateurscommunicatie, in de manier waarop trouwe donateurs worden bedankt en betrokken, en in de zorgvuldigheid waarmee gevoelige gesprekken worden gevoerd. Dat vraagt om afstemming tussen teams die in veel organisaties nog gescheiden opereren: werving, relatiebeheer en soms een aparte legacy-functionaris.`] },
          { h: 'Voor de praktijk', paras: [`Voor kleinere organisaties die nog geen apart nalatenschapsprogramma hebben, is de belangrijkste stap niet het opzetten van een grote campagne, maar het inbouwen van ruimte in bestaande donateurscontacten om het onderwerp bespreekbaar te maken. Een groeiende opbrengst is geen garantie, maar wel een aanwijzing dat de aandacht die de sector aan dit thema besteedt, zich uitbetaalt in daadwerkelijke inkomsten.`] }
        ] },
        { id: 'geven-in-nederland-2026', tag: 'Onderzoek', date: '15 mei 2026', title: 'Geven in Nederland 2026: groei op papier, kwetsbaarheid eronder', excerpt: 'Bijna 5,5 miljard euro aan giften: op het eerste gezicht gezond. Wie verder kijkt, ziet een sector die op een smallere basis steunt.', source: 'Geven in Nederland 2026, Centrum voor Filantropische Studies, Vrije Universiteit Amsterdam.', body: [
          { h: '', paras: [`Eens in de twee jaar brengt het Centrum voor Filantropische Studies van de Vrije Universiteit Amsterdam het rapport Geven in Nederland uit. De editie van 2026, die het geefgedrag van 2024 in kaart brengt, laat een bedrag zien van bijna 5,5 miljard euro aan giften aan goede doelen. Op het eerste gezicht een gezond cijfer. Wie verder kijkt, ziet een sector die op een smallere basis steunt dan de totaalsom doet vermoeden.`] },
          { h: 'Een groter bedrag, een kleinere groep', paras: [`Het aandeel van het bruto binnenlands product dat naar filantropie gaat, daalde licht ten opzichte van eerdere jaren. Driekwart van de Nederlandse huishoudens geeft nog altijd geld of goederen, en een vergelijkbaar aandeel zet zich vrijwillig in. Maar de onderzoekers signaleren dat een kleinere en kapitaalkrachtigere groep gevers, bedrijven en nalaters verantwoordelijk is voor een steeds groter deel van het totaal. Voor organisaties die op brede achterban leunen, is dat een signaal om aandacht te blijven besteden aan spreiding van het geefpubliek, niet alleen aan de omvang ervan.`] },
          { h: 'Nalatenschappen als groeimotor', paras: [`Het meest uitgesproken groeicijfer komt van nalatenschappen: met een opbrengst van 512 miljoen euro noteren giften uit erfenissen een stijging van dertien procent, de grootste toename sinds het onderzoek bestaat. Voor fondsenwervers die zich richten op langetermijnrelaties met donateurs is dit een bevestiging van een ontwikkeling die al langer zichtbaar was: nalatenschapswerving verschuift van een nichethema naar een structureel onderdeel van de mix.`] },
          { h: 'Bedrijfsfilantropie: andere lens, ander beeld', paras: [`Voor bedrijfsgiften hanteert het onderzoek een aangepaste meetmethode, waardoor vergelijkingen met eerdere jaren minder eenduidig zijn. Wel is duidelijk waar het bedrijfsleven zijn geld naartoe brengt: sport en recreatie, onderwijs en onderzoek, gezondheid en cultuur voeren de lijst aan. Voor organisaties die bedrijven als financieringsbron overwegen, is dit een reden om de aansluiting bij deze thema's scherp in beeld te houden.`] },
          { h: 'Wat dit betekent voor de praktijk', paras: [`Hoogleraar filantropie René Bekkers noemt 2024 in het voorwoord een politiek roerig jaar, met bezuinigingen op internationale samenwerking, druk op de giftenaftrek en toegenomen regeldruk voor vrijwilligersorganisaties als achtergrond. Een deel van die onzekerheden is inmiddels opgelost, een deel speelt in 2026 nog altijd. Voor wie fondsen werft, is de les van dit rapport niet dat het slecht gaat, maar dat de fundamenten smaller worden. Overzicht over wie werkelijk bijdraagt, en vertrouwen opbouwen bij een bredere kring van gevers, wegen zwaarder dan ooit.`] }
        ] },
        { id: 'trust-based-philanthropy', tag: 'Vakkennis', date: '24 apr 2026', title: 'Trust-based philanthropy: waarom sommige fondsen niet meer om een projectplan vragen', excerpt: 'Steeds meer regelingen breken bewust met de klassieke fondsaanvraag. Niet minder voorbereiding, maar een andere soort voorbereiding.', source: 'Fondswervingonline.nl, regeling Creativity Pioneers Fund, Open Call 2026.', body: [
          { h: '', paras: [`Wie gewend is aan de klassieke fondsaanvraag, een projectplan, een geoormerkte begroting, verantwoording per kostenpost, komt in toenemende mate regelingen tegen die dat patroon bewust doorbreken. Een voorbeeld is een internationale subsidie voor creatieve en culturele non-profitorganisaties, die geen projectvoorstel vraagt maar een portret van de organisatie als geheel: wie ben je, wie bereik je, hoe zet je je missie in voor maatschappelijke verandering.`] },
          { h: 'Wat trust-based philanthropy anders maakt', paras: [`De achterliggende gedachte is dat organisaties die dagelijks in de uitvoering staan, zelf het beste weten waar middelen het hardst nodig zijn. Dat vertaalt zich in drie kenmerken: vrij besteedbare financiering zonder geoormerkt budget, eenvoudige aanvraagprocedures zonder uitgebreide projectbegroting, en een langduriger relatie met de financier in plaats van een korte projectcyclus met verantwoording achteraf.`] },
          { h: 'Voor wie dit relevant is', paras: [`Deze benadering is nog geen mainstream, maar wint terrein, met name bij fondsen die zich richten op kleinere of opkomende organisaties en op sectoren die traditioneel moeite hebben om aan te sluiten bij projectlogica. Culturele en creatieve non-profitorganisaties zijn daar een voorbeeld van: hun werk laat zich niet altijd vangen in een aanvraag met vooraf gedefinieerde outputs en indicatoren.`] },
          { h: 'De andere kant van de medaille', paras: [`Het ontbreken van een projectplan-vereiste betekent niet dat de beoordeling losser is. Fondsen die deze aanpak hanteren, kijken juist scherp naar de organisatie zelf: de helderheid van de missie, de aantoonbare verbinding met de doelgroep en de geloofwaardigheid van het verhaal dat wordt verteld. Een aanvraag zonder projectplan vraagt dus niet om minder voorbereiding, maar om een andere soort voorbereiding, een die begint bij het scherp krijgen van wie je bent als organisatie, niet bij wat je gaat uitvoeren.`] },
          { h: 'Wat dit betekent voor de aanvraagpraktijk', paras: [`Voor fondsenwervers is de praktische les dat het onderscheid tussen "project" en "projectplan" er hier meer dan ooit toe doet. Een project is wat je doet; een projectplan is het document waarmee je dat aan een financier voorlegt. Trust-based fondsen vragen om het eerste te kunnen uitleggen zonder het tweede als formaliteit in te leveren. Voor organisaties die dit soort financiering overwegen, is het raadzaam om na te gaan welke fondsen in hun werkterrein deze filosofie hanteren, en de aanvraag daarop aan te passen, niet door minder te doen, maar door anders te schrijven.`] }
        ] },
        { id: 'subsidielandschap-2026', tag: 'Subsidies', date: '3 apr 2026', title: 'Het subsidielandschap van 2026: minder vanzelfsprekend, niet minder kansrijk', excerpt: 'Sommige regelingen worden ruimer, andere krimpen, en de eisen aan aanvragen worden over de hele linie strenger.', source: 'Subsidiebureau Nederland, overzicht Prinsjesdag 2025 (gepresenteerd september 2025) en subsidiekansen voor 2026.', body: [
          { h: '', paras: [`Op Prinsjesdag 2025, de derde dinsdag van september, traditiegetrouw het moment waarop het kabinet de Miljoenennota en Rijksbegroting voor het volgende jaar presenteert, zijn de contouren van het subsidiejaar 2026 zichtbaar geworden. Het beeld is gemengd: sommige regelingen worden ruimer, andere krimpen of verdwijnen, en de eisen aan aanvragen worden over de hele linie strenger.`, `Nu we medio 2026 zijn, is dit voor fondsenwervers geen terugblik maar een praktisch ijkpunt: een groot deel van de regelingen uit die begroting loopt dit hele jaar door, aanvraagvensters en deadlines vallen middenin 2026, en wie nu een project voorbereidt voor het komende aanvraagseizoen, plant feitelijk al toe naar Prinsjesdag 2026, de derde dinsdag van september, dit jaar op 15 september. Met andere woorden: dit is het moment om te toetsen of je organisatie de huidige regelingen benut vóórdat de volgorde weer verschuift.`] },
          { h: 'Drie regelingen om in de gaten te houden', paras: [`Voor de non-profitsector springen dit jaar drie regelingen in het oog. De Maatschappelijke Diensttijd blijft relevant voor organisaties die jongeren bij hun activiteiten willen betrekken. LEADER biedt kansen voor samenwerkingsverbanden in het landelijk gebied, mits het project aansluit bij de Lokale Ontwikkelingsstrategie van de regio en er cofinanciering beschikbaar is, de betrokkenheid van gemeente of provincie is daarbij vaak doorslaggevend. En de Subsidieregeling Duurzaam Maatschappelijk Vastgoed (DUMAVA) blijft een van de belangrijkste routes voor organisaties met eigen gebouwen die willen verduurzamen, nu energiekosten en klimaatdoelen verduurzaming steeds minder vrijblijvend maken.`] },
          { h: 'Wat er verder verandert', paras: [`Vanaf 2026 wordt energiezuinige ventilatie toegevoegd aan de Investeringssubsidie duurzame energie en energiebesparing (ISDE). De SPUK Kansrijke Wijk krijgt een vervolg, met meer lokale beleidsvrijheid en een eenvoudigere aanvraagprocedure voor gemeenten die investeren in kwetsbare wijken. En voor onderwijs en onderzoek is in 2026 in totaal 77 miljoen euro gereserveerd voor programma's als Ontwikkelkracht, Npuls en Biotech Booster.`] },
          { h: 'De rode draad: voorbereiding weegt zwaarder', paras: [`Wat deze regelingen gemeen hebben, is dat beoordelaars kritischer kijken naar maatschappelijke meerwaarde, financiële onderbouwing, samenwerking en uitvoerbaarheid. Een sterk idee is niet langer voldoende; de onderbouwing en de aantoonbare uitvoeringscapaciteit van de aanvrager wegen even zwaar mee. Dat betekent voor veel organisaties dat het traject van projectvoorbereiding eerder moet beginnen dan voorheen.`] },
          { h: 'Fondsen als aanvulling, niet als reserveoptie', paras: [`Naast overheidsregelingen blijven vermogensfondsen een cruciale financieringsbron, juist omdat zij meer ruimte bieden voor maatwerk dan de vaak programmatische overheidssubsidies. In de praktijk is het niet subsidie óf fonds, maar de combinatie van beide die grotere maatschappelijke projecten haalbaar maakt. Wie deze twee sporen vanaf de start van een project naast elkaar legt, in plaats van pas na een afwijzing naar een fonds te kijken, staat aantoonbaar sterker.`] }
        ] }
      ];

export const resources = [
        { type: 'Template', format: 'DOCX', title: 'Projectplan sjabloon' },
        { type: 'Template', format: 'XLSX', title: 'Begrotingsmodel fondsaanvraag' },
        { type: 'Praktijkgids', format: 'PDF', title: 'Particuliere fondsen benaderen' },
        { type: 'Checklist', format: 'PDF', title: 'Aanvraag indienen zonder fouten' },
        { type: 'Template', format: 'DOCX', title: 'Voorbeeld motivatiebrief' },
        { type: 'Praktijkgids', format: 'PDF', title: 'Meerjarenbegroting opstellen' }
      ];

export const sessions = [
        { day: '18', month: 'jul', title: 'Intervisie: lastige casussen bespreken', time: '10:00', host: 'o.l.v. Aisha El Amrani', mode: 'Online' },
        { day: '02', month: 'sep', title: 'Werksessie: begroting die aansluit bij fondseisen', time: '13:30', host: 'o.l.v. Jeroen Visscher', mode: 'Utrecht' },
        { day: '24', month: 'sep', title: 'Kennistafel: major donors werven', time: '15:00', host: 'o.l.v. Bram Koster', mode: 'Online' }
      ];

export const blogPosts = [
        { tag: 'Kennisdeling', title: 'Wat we leerden van vijf afgewezen aanvragen', excerpt: 'Een eerlijke terugblik op afwijzingen bij particuliere fondsen, en wat we de volgende keer anders deden.', author: 'Redactie', role: 'Het Fondsenwervers Collectief' },
        { tag: 'Praktijk', title: 'Major donors werven zonder groot netwerk', excerpt: 'Praktische aanpak voor kleinere organisaties die net beginnen met grote-givers-strategie.', author: 'Redactie', role: 'Het Fondsenwervers Collectief' },
        { tag: 'Intervisie', title: 'Omgaan met een subsidie die net te laat kwam', excerpt: 'Hoe je een gemiste deadline ombuigt naar een sterkere aanvraag voor de volgende ronde.', author: 'Redactie', role: 'Het Fondsenwervers Collectief' }
      ];

export const questions = [
        { title: 'Hoe onderbouw je een meerjarige aanvraag bij een klein fonds?', author: 'Een lid', role: 'Fondsenwerver', answers: 6 },
        { title: 'Wie heeft ervaring met co-financiering tussen gemeente en provincie?', author: 'Een lid', role: 'Zelfstandig fondsenwerver', answers: 3 },
        { title: 'Beste aanpak voor een eerste kennismaking met een nieuw fonds?', author: 'Een lid', role: 'Fondsenwerver', answers: 9 },
        { title: 'Hoe rapporteer je impact aan een fonds zonder overdreven data te verzamelen?', author: 'Een lid', role: 'Fondsenwerver', answers: 4 }
      ];

export const members = [
        { name: 'Lid van het Collectief', role: 'Fondsenwerver', email: 'zichtbaar na registratie' },
        { name: 'Lid van het Collectief', role: 'Zelfstandig fondsenwerver', email: 'zichtbaar na registratie' },
        { name: 'Lid van het Collectief', role: 'Fondsenwerver', email: 'zichtbaar na registratie' },
        { name: 'Lid van het Collectief', role: 'Fondsenwerver', email: 'zichtbaar na registratie' }
      ];

export const vacancies = [
        { title: 'Relatiemanager Fondsenwerving', org: 'Stichting AAP', location: 'Almere', type: 'Parttime', tags: ['Dierenwelzijn', 'Relatiebeheer'], url: 'https://www.aap.nl/vacatures-betaald-werken/vacature-relatiemanager-fondsenwerving/' },
        { title: 'Senior Relatiemanager & Fondsenwerver', org: 'De Natuur en Milieufederaties', location: 'Utrecht', type: 'Parttime', tags: ['Natuur & milieu', 'Major donors'], url: 'https://www.natuurenmilieufederaties.nl/vacature/de-natuur-en-milieufederaties-zoeken-een-commerciele-en-bevlogen-senior-relatiemanager-fondsenwerver/' },
        { title: 'Relatiemanager Fondsenwerving', org: 'Nationaal Fonds Kinderhulp', location: 'Nederland', type: 'Parttime', tags: ['Kind & jeugd', 'Relatiebeheer'], url: 'https://kinderhulp.nl/nieuws/vacature-relatiemanager-fondsenwerving-24-uur/' },
        { title: 'Fondsenwerver', org: 'Goededoelenorganisatie', location: 'Nederland', type: 'Fulltime', tags: ['Goede doelen', 'Fondsenwerving'], url: 'https://www.oneworld.nl/job/fondsenwerver-17/' },
        { title: 'Fondsenwerver, diverse organisaties', org: 'Diverse organisaties', location: 'Nederland', type: 'Wisselend', tags: ['Diverse thema’s', 'Fondsenwerving'], url: 'https://nl.indeed.com/q-fondsenwerver-vacatures.html' },
        { title: 'Coördinator Fondsenwerving & Partnerships', org: 'Goededoelenorganisatie', location: 'Nederland', type: 'Parttime', tags: ['Gezondheid', 'Partnerships'], url: 'https://nl.indeed.com/q-fondsenwerver-vacatures.html' }
      ];

export const newsItems = [
        { tag: 'Subsidies', date: '3 jul 2026', title: 'Nieuwe ronde Fonds voor Cultuurparticipatie geopend', excerpt: 'Culturele instellingen kunnen tot 1 oktober aanvragen indienen voor participatieprojecten in het onderwijs.' },
        { tag: 'Regelgeving', date: '28 jun 2026', title: 'Wat verandert er in de ANBI-regelgeving per 2027?', excerpt: 'Een overzicht van de belangrijkste wijzigingen en wat organisaties nu al kunnen voorbereiden.' },
        { tag: 'Vakkennis', date: '19 jun 2026', title: 'Vijf trends in fondsenwerving voor 2026', excerpt: 'Van AI-ondersteuning tot kortere aanvraagtermijnen: dit zien we terug in de sector dit jaar.' }
      ];

export const testimonials = [
        { quote: 'Subsidie Kompas scheelde ons dagen zoekwerk. We vonden een fonds waar we nooit aan gedacht hadden.', name: 'Lid van het Collectief', role: 'Fondsenwerver' },
        { quote: 'Als kleine stichting hebben we geen fondsenwerver in dienst. Dit platform gaf ons houvast waar we het zelf moesten doen.', name: 'Lid van het Collectief', role: 'Kleine organisatie' }
      ];

export const videos = [
        { title: 'Wat doet een fondsenwerver eigenlijk?', duration: '6:12', level: 'Introductie' },
        { title: 'De basis van een goed projectplan', duration: '9:45', level: 'Introductie' },
        { title: 'Subsidie of particulier fonds: wat kies je?', duration: '8:03', level: 'Verdieping' },
        { title: 'Een aanvraag schrijven die opvalt', duration: '11:20', level: 'Verdieping' },
        { title: 'Omgaan met een afwijzing', duration: '5:37', level: 'Praktijk' },
        { title: 'Relatiebeheer met fondsen op lange termijn', duration: '10:02', level: 'Praktijk' }
      ];

export const CHAT_SYSTEM_PROMPT = `Je bent "Collie", de digitale assistent van Het Fondsenwervers Collectief \u2014 een Nederlands kennisplatform voor fondsenwerving en subsidies.

Je helpt bezoekers vriendelijk, duidelijk en kort met vragen over:
- Het platform: een kennisplatform met vakkennis, ervaring en de AI-tool Subsidie Kompas.
- Subsidie Kompas: een aparte AI-assistent (bereikbaar via de knop "Probeer Subsidie Kompas" en de pagina Subsidie Kompas) die helpt bij het vinden van passende fondsen, een fondsenwervende strategie en begeleiding bij de aanvraag.
- De drie paden: Fondsenwervers (professionaliseren, vakkennis, netwerk), Organisaties (zelf financiering vinden voor een project) en Ori\u00ebnterend / Fondsenwerver worden (video's, cursus of masterclass).
- Het Collectief: netwerk & intervisie, kennisdeling, vraag & antwoord, ledenprofielen en vacatures (login vereist voor contactgegevens).
- Actueel: nieuws, verdiepende artikelen en actuele regelgeving over fondsenwerving en subsidies.

Baseer antwoorden alleen op deze website-informatie. Verzin geen prijzen, voorwaarden, cijfers of bedrijfsinformatie die hier niet genoemd is. Als je het antwoord niet zeker weet, zeg dit eerlijk en verwijs door naar Subsidie Kompas (voor concrete subsidievragen) of het contactformulier.

Beantwoord geen vragen die niets met dit platform te maken hebben; verwijs dan vriendelijk terug naar waar je wel mee kan helpen. Stel maximaal \u00e9\u00e9n vervolgvraag tegelijk. Vraag nooit om gevoelige persoonsgegevens. Houd antwoorden kort (2-4 zinnen), in gewone, natuurlijke taal, aansprekend met "u" of "je" consistent met de vraag van de bezoeker.

Opmaak: gebruik geen markdown-opmaak zoals sterretjes voor vet (**tekst**). Gebruik gewone platte tekst. Voor een opsomming gebruik je een liggend streepje "-" gevolgd door een dubbele punt waar relevant, elk op een nieuwe regel, niet sterretjes of nummering.`;
