-- Bestaande tabellen: alleen aangemaakt als ze nog niet bestaan.
-- Verandert niets aan kolommen of data van een bestaande tabel.

create extension if not exists "pgcrypto";

-- Leden en hun abonnement.
create table if not exists profiles (
  id uuid primary key references auth.users on delete cascade,
  first_name text,
  last_name text,
  email text,
  member_type text,
  motivation text,
  status text not null default 'pending',       -- pending | approved | rejected
  role text not null default 'member',          -- member | admin
  subscription_tier text not null default 'free', -- free | pro | premium
  subscription_active boolean not null default false,
  trial_started_at timestamptz,
  trial_ends_at timestamptz,
  subscription_started_at timestamptz,
  subscription_ends_at timestamptz,
  stripe_customer_id text,
  stripe_subscription_id text,
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  approved_by uuid references auth.users
);

-- Redactionele inhoud. Alle tabellen delen dezelfde vorm: status + sortering.
create table if not exists news_articles (
  id bigint generated by default as identity primary key,
  status text not null default 'draft',
  tag text, date text, title text, excerpt text, body text, url text,
  sort_order int default 0,
  created_at timestamptz not null default now()
);

create table if not exists blog_posts (
  id bigint generated by default as identity primary key,
  status text not null default 'draft',
  tag text, title text, excerpt text, body text, author text, date text,
  sort_order int default 0,
  created_at timestamptz not null default now()
);

create table if not exists videos (
  id bigint generated by default as identity primary key,
  status text not null default 'draft',
  title text, duration text, level text, url text,
  sort_order int default 0,
  created_at timestamptz not null default now()
);

create table if not exists resources (
  id bigint generated by default as identity primary key,
  status text not null default 'draft',
  type text, format text, title text, url text,
  sort_order int default 0,
  created_at timestamptz not null default now()
);

create table if not exists sessions (
  id bigint generated by default as identity primary key,
  status text not null default 'draft',
  day text, month text, title text, time text, host text, mode text,
  sort_order int default 0,
  created_at timestamptz not null default now()
);

create table if not exists vacancies (
  id bigint generated by default as identity primary key,
  status text not null default 'draft',
  title text, org text, location text, type text, tags text[], url text,
  sort_order int default 0,
  created_at timestamptz not null default now()
);

create table if not exists course_modules (
  id bigint generated by default as identity primary key,
  status text not null default 'draft',
  title text, description text, duration text, level text,
  sort_order int default 0,
  created_at timestamptz not null default now()
);

create table if not exists masterclasses (
  id bigint generated by default as identity primary key,
  status text not null default 'draft',
  title text, description text, date text, host text, location text,
  sort_order int default 0,
  created_at timestamptz not null default now()
);

-- Aanmeldingen die goedkeuring vragen.
create table if not exists applications (
  id bigint generated by default as identity primary key,
  profile_id uuid references profiles on delete cascade,
  first_name text, last_name text, email text, member_type text, motivation text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

-- Sleutel-waarde: teksten van de publieke website.
create table if not exists site_content (
  key text primary key,
  value text,
  updated_at timestamptz not null default now()
);

-- Sleutel-waarde: platforminstellingen. Naam volgt de bestaande code.
create table if not exists site_settings (
  key text primary key,
  value text,
  updated_at timestamptz not null default now()
);

-- RLS: gepubliceerde inhoud is openbaar, de rest alleen voor beheerders.
create or replace function is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from profiles where id = auth.uid() and role = 'admin');
$$;

do $$
declare t text;
begin
  foreach t in array array['news_articles','blog_posts','videos','resources','sessions','vacancies','course_modules','masterclasses']
  loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "gepubliceerd is openbaar" on %I', t);
    execute format($f$
      create policy "gepubliceerd is openbaar" on %I
        for select using (status = 'published' or is_admin())
    $f$, t);
    execute format('drop policy if exists "beheer schrijft" on %I', t);
    execute format($f$
      create policy "beheer schrijft" on %I
        for all using (is_admin()) with check (is_admin())
    $f$, t);
  end loop;
end $$;

alter table profiles enable row level security;
drop policy if exists "eigen profiel lezen" on profiles;
create policy "eigen profiel lezen" on profiles
  for select using (id = auth.uid() or is_admin());
drop policy if exists "eigen profiel wijzigen" on profiles;
create policy "eigen profiel wijzigen" on profiles
  for update using (id = auth.uid() or is_admin());
drop policy if exists "beheer beheert profielen" on profiles;
create policy "beheer beheert profielen" on profiles
  for all using (is_admin()) with check (is_admin());

alter table site_content enable row level security;
drop policy if exists "teksten zijn openbaar" on site_content;
create policy "teksten zijn openbaar" on site_content for select using (true);
drop policy if exists "beheer schrijft teksten" on site_content;
create policy "beheer schrijft teksten" on site_content
  for all using (is_admin()) with check (is_admin());

-- Instellingen bevatten sleutels: alleen beheerders.
alter table site_settings enable row level security;
drop policy if exists "beheer beheert instellingen" on site_settings;
create policy "beheer beheert instellingen" on site_settings
  for all using (is_admin()) with check (is_admin());

alter table applications enable row level security;
drop policy if exists "eigen aanvraag" on applications;
create policy "eigen aanvraag" on applications
  for select using (profile_id = auth.uid() or is_admin());
drop policy if exists "aanvraag indienen" on applications;
create policy "aanvraag indienen" on applications
  for insert with check (profile_id = auth.uid());
drop policy if exists "beheer beheert aanvragen" on applications;
create policy "beheer beheert aanvragen" on applications
  for all using (is_admin()) with check (is_admin());
