-- Fondsen, subsidieregelingen en hun deadlines.
-- Gebruikt door data/services/deadlines.js en data/services/funding.js.

create table if not exists funders (
  id bigint generated by default as identity primary key,
  naam text not null,
  type text,                    -- Vermogensfonds | Gemeente | Provincie | Corporate Foundation | Rijksfonds
  website text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists themas (
  id bigint generated by default as identity primary key,
  naam text not null unique
);

create table if not exists regios (
  id bigint generated by default as identity primary key,
  naam text not null unique
);

create table if not exists subsidieregelingen (
  id bigint generated by default as identity primary key,
  naam text not null,
  funder_id bigint references funders on delete set null,
  bedrag_min numeric,
  bedrag_max numeric,
  omschrijving text,
  voorwaarden text,
  url text,
  is_active boolean not null default true,
  is_premium boolean not null default false,   -- alleen voor Premium-leden
  created_at timestamptz not null default now()
);

-- De tijdlijn: status en deadline per regeling. Geen gedupliceerde gegevens;
-- naam, bedrag en verstrekker komen via de relatie.
create table if not exists subsidieregelingen_tijdlijn (
  id bigint generated by default as identity primary key,
  regeling_id bigint not null references subsidieregelingen on delete cascade,
  status text not null default 'Open',  -- Open | Binnenkort | Doorlopend | Aangekondigd | Budget uitgeput | Gesloten
  deadline_datum date,                  -- leeg bij een doorlopende regeling
  opent_datum date,
  dagen_resterend int generated always as (
    case when deadline_datum is null then null
         else (deadline_datum - current_date) end
  ) stored,
  toelichting text,
  updated_at timestamptz not null default now()
);

create table if not exists subsidieregeling_themas (
  regeling_id bigint references subsidieregelingen on delete cascade,
  thema_id bigint references themas on delete cascade,
  primary key (regeling_id, thema_id)
);

create table if not exists subsidieregeling_regios (
  regeling_id bigint references subsidieregelingen on delete cascade,
  regio_id bigint references regios on delete cascade,
  primary key (regeling_id, regio_id)
);

-- Indexen voor sorteren en filteren op deadline.
create index if not exists tijdlijn_status_idx on subsidieregelingen_tijdlijn (status);
create index if not exists tijdlijn_deadline_idx on subsidieregelingen_tijdlijn (deadline_datum);
create index if not exists tijdlijn_status_deadline_idx on subsidieregelingen_tijdlijn (status, deadline_datum);
create index if not exists tijdlijn_regeling_idx on subsidieregelingen_tijdlijn (regeling_id);
create index if not exists regelingen_funder_idx on subsidieregelingen (funder_id);
create index if not exists regelingen_naam_idx on subsidieregelingen using gin (to_tsvector('dutch', naam));

-- RLS. De blur in de frontend is presentatie; de scheiding zit hier.
alter table funders enable row level security;
alter table subsidieregelingen enable row level security;
alter table subsidieregelingen_tijdlijn enable row level security;
alter table themas enable row level security;
alter table regios enable row level security;
alter table subsidieregeling_themas enable row level security;
alter table subsidieregeling_regios enable row level security;

create or replace function has_premium() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from profiles
    where id = auth.uid()
      and subscription_tier = 'premium'
      and subscription_active = true
  );
$$;

-- Openbare regelingen voor iedereen; premium alleen met Premium.
drop policy if exists "regelingen lezen" on subsidieregelingen;
create policy "regelingen lezen" on subsidieregelingen
  for select using (is_active and (not is_premium or has_premium() or is_admin()));

drop policy if exists "tijdlijn lezen" on subsidieregelingen_tijdlijn;
create policy "tijdlijn lezen" on subsidieregelingen_tijdlijn
  for select using (
    exists (
      select 1 from subsidieregelingen r
      where r.id = regeling_id
        and r.is_active
        and (not r.is_premium or has_premium() or is_admin())
    )
  );

drop policy if exists "funders lezen" on funders;
create policy "funders lezen" on funders for select using (is_active);
drop policy if exists "themas lezen" on themas;
create policy "themas lezen" on themas for select using (true);
drop policy if exists "regios lezen" on regios;
create policy "regios lezen" on regios for select using (true);
drop policy if exists "thema-koppeling lezen" on subsidieregeling_themas;
create policy "thema-koppeling lezen" on subsidieregeling_themas for select using (true);
drop policy if exists "regio-koppeling lezen" on subsidieregeling_regios;
create policy "regio-koppeling lezen" on subsidieregeling_regios for select using (true);

do $$
declare t text;
begin
  foreach t in array array['funders','subsidieregelingen','subsidieregelingen_tijdlijn','themas','regios','subsidieregeling_themas','subsidieregeling_regios']
  loop
    execute format('drop policy if exists "beheer schrijft fondsen" on %I', t);
    execute format($f$
      create policy "beheer schrijft fondsen" on %I
        for all using (is_admin()) with check (is_admin())
    $f$, t);
  end loop;
end $$;

-- Realtime: de Deadlines-pagina volgt wijzigingen live.
alter publication supabase_realtime add table subsidieregelingen_tijdlijn;
alter publication supabase_realtime add table subsidieregelingen;
