-- De werkomgeving van een lid: profiel, projecten, documentatie, gesprekken.
-- Alles per profile_id, dus RLS is eenvoudig: een lid ziet alleen eigen rijen.
-- Vervangt de localStorage-opslag in data/services/workspace.js.

create table if not exists organisatieprofielen (
  profile_id uuid primary key references profiles on delete cascade,
  naam text,
  website text,
  rechtsvorm text,
  anbi boolean,
  sector text,
  missie text,
  strategie text,
  werkgebied text,
  themas text[],
  doelgroepen text[],
  jaaromzet text,
  financieringsmix text,
  tone_of_voice text,
  updated_at timestamptz not null default now()
);

create table if not exists projecten (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references profiles on delete cascade,
  naam text,
  programma text,
  doelgroep text,
  looptijd text,
  regio text,
  omschrijving text,
  begroting numeric,
  gevraagd numeric,
  eigen_bijdrage numeric,
  status text default 'actief',      -- actief | afgerond | gepauzeerd
  prioriteit text default 'normaal', -- laag | normaal | hoog
  voortgang int default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Eerder aangevraagde fondsen en hun uitkomst.
create table if not exists project_aanvragen (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projecten on delete cascade,
  fonds text,
  jaar text,
  bedrag numeric,
  uitkomst text,      -- toegekend | afgewezen | in behandeling
  toelichting text
);

create table if not exists project_cofinanciers (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projecten on delete cascade,
  naam text,
  bedrag numeric,
  status text        -- toegezegd | aangevraagd | verkennend
);

-- Het dekkingsplan: welke regelingen bij dit project worden aangevraagd.
create table if not exists project_regelingen (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projecten on delete cascade,
  regeling_id bigint references subsidieregelingen on delete set null,
  regeling_naam text,          -- vrije invoer als de regeling niet in de database staat
  bedrag numeric,
  status text default 'gepland',
  herinnering_dagen int,
  unique (project_id, regeling_id)
);

create table if not exists project_documenten (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projecten on delete cascade,
  naam text,
  soort text,           -- projectplan | begroting | dekkingsplan | overig
  grootte bigint,
  opslagpad text,       -- pad in de bucket project-documenten
  tekst text,           -- uitgelezen inhoud, als context voor de assistent
  created_at timestamptz not null default now()
);

-- Door de assistent gegenereerde documenten.
create table if not exists documentatie (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references profiles on delete cascade,
  project_id bigint references projecten on delete set null,
  naam text,
  soort text,           -- word | excel | pdf
  versie int not null default 1,
  grootte bigint,
  opslagpad text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists documentatie_versies (
  id bigint generated by default as identity primary key,
  document_id bigint not null references documentatie on delete cascade,
  versie int not null,
  grootte bigint,
  opslagpad text,
  created_at timestamptz not null default now(),
  unique (document_id, versie)
);

create table if not exists gesprekken (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references profiles on delete cascade,
  titel text,
  berichten jsonb not null default '[]',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Voorkeuren van een lid.
create table if not exists lid_voorkeuren (
  profile_id uuid primary key references profiles on delete cascade,
  zichtbaar_in_ledenlijst boolean not null default true,
  herinnering_mail boolean not null default true,
  herinnering_dagen int not null default 14,
  updated_at timestamptz not null default now()
);

create index if not exists projecten_profile_idx on projecten (profile_id);
create index if not exists documentatie_profile_idx on documentatie (profile_id);
create index if not exists gesprekken_profile_idx on gesprekken (profile_id, updated_at desc);

-- RLS: eigen rijen, niets meer.
do $$
declare t text;
begin
  foreach t in array array['organisatieprofielen','projecten','documentatie','gesprekken','lid_voorkeuren']
  loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "eigen rijen" on %I', t);
    execute format($f$
      create policy "eigen rijen" on %I
        for all using (profile_id = auth.uid()) with check (profile_id = auth.uid())
    $f$, t);
  end loop;
end $$;

-- Kindtabellen: via het bovenliggende project of document.
alter table project_aanvragen enable row level security;
alter table project_cofinanciers enable row level security;
alter table project_regelingen enable row level security;
alter table project_documenten enable row level security;
alter table documentatie_versies enable row level security;

do $$
declare t text;
begin
  foreach t in array array['project_aanvragen','project_cofinanciers','project_regelingen','project_documenten']
  loop
    execute format('drop policy if exists "via eigen project" on %I', t);
    execute format($f$
      create policy "via eigen project" on %I
        for all using (
          exists (select 1 from projecten p where p.id = project_id and p.profile_id = auth.uid())
        ) with check (
          exists (select 1 from projecten p where p.id = project_id and p.profile_id = auth.uid())
        )
    $f$, t);
  end loop;
end $$;

drop policy if exists "via eigen document" on documentatie_versies;
create policy "via eigen document" on documentatie_versies
  for all using (
    exists (select 1 from documentatie d where d.id = document_id and d.profile_id = auth.uid())
  ) with check (
    exists (select 1 from documentatie d where d.id = document_id and d.profile_id = auth.uid())
  );

-- De ledenlijst: alleen leden die zichtbaar willen zijn. Geen contactgegevens.
create or replace view ledenlijst as
  select p.id, p.first_name, p.last_name, p.member_type
  from profiles p
  join lid_voorkeuren v on v.profile_id = p.id
  where p.status = 'approved' and v.zichtbaar_in_ledenlijst;
