-- Beheerbare inhoud: FAQ, stappen, pagina's, SEO, flags, logboek, verbruik.

create table if not exists kompas_faq (
  id bigint generated by default as identity primary key,
  sectie text not null default 'Algemeen',
  vraag text not null,
  antwoord text not null,
  sortering int not null default 0,
  status text not null default 'draft',
  updated_at timestamptz not null default now()
);

create table if not exists kompas_stappen (
  id bigint generated by default as identity primary key,
  nummer text,
  titel text not null,
  tekst text,
  sortering int not null default 0,
  status text not null default 'draft'
);

-- Pagina's en hun SEO. slug is het routepad zonder '#'.
create table if not exists paginas (
  slug text primary key,
  titel text,
  seo_titel text,
  seo_omschrijving text,
  seo_afbeelding text,
  in_navigatie boolean not null default false,
  navigatie_label text,
  navigatie_sortering int default 0,
  status text not null default 'published',
  updated_at timestamptz not null default now()
);

-- Systeemteksten van de assistent, beheerbaar zonder code.
create table if not exists ai_prompts (
  key text primary key,          -- bijv. kompas.system | collie.system
  label text,
  prompt text,
  updated_at timestamptz not null default now()
);

create table if not exists ai_startsuggesties (
  id bigint generated by default as identity primary key,
  tekst text not null,
  sortering int not null default 0,
  status text not null default 'published'
);

create table if not exists feature_flags (
  key text primary key,
  label text,
  aan boolean not null default false,
  toelichting text,
  updated_at timestamptz not null default now()
);

-- Logboek van beheeracties.
create table if not exists audit_log (
  id bigint generated by default as identity primary key,
  profile_id uuid references profiles on delete set null,
  actie text not null,
  tabel text,
  record_id text,
  details jsonb,
  created_at timestamptz not null default now()
);

-- Verbruik per aanroep van de assistent. Vult de accountpagina.
create table if not exists ai_verbruik (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references profiles on delete cascade,
  gesprek_id bigint references gesprekken on delete set null,
  model text,
  tokens_in int,
  tokens_uit int,
  kosten numeric,
  created_at timestamptz not null default now()
);

create index if not exists verbruik_profile_idx on ai_verbruik (profile_id, created_at desc);
create index if not exists audit_created_idx on audit_log (created_at desc);

alter table kompas_faq enable row level security;
alter table kompas_stappen enable row level security;
alter table paginas enable row level security;
alter table ai_startsuggesties enable row level security;
alter table feature_flags enable row level security;
alter table ai_prompts enable row level security;
alter table audit_log enable row level security;
alter table ai_verbruik enable row level security;

drop policy if exists "faq openbaar" on kompas_faq;
create policy "faq openbaar" on kompas_faq
  for select using (status = 'published' or is_admin());
drop policy if exists "stappen openbaar" on kompas_stappen;
create policy "stappen openbaar" on kompas_stappen
  for select using (status = 'published' or is_admin());
drop policy if exists "paginas openbaar" on paginas;
create policy "paginas openbaar" on paginas
  for select using (status = 'published' or is_admin());
drop policy if exists "suggesties openbaar" on ai_startsuggesties;
create policy "suggesties openbaar" on ai_startsuggesties
  for select using (status = 'published' or is_admin());
drop policy if exists "flags openbaar" on feature_flags;
create policy "flags openbaar" on feature_flags for select using (true);

-- Prompts en logboek: alleen beheerders.
drop policy if exists "beheer beheert prompts" on ai_prompts;
create policy "beheer beheert prompts" on ai_prompts
  for all using (is_admin()) with check (is_admin());
drop policy if exists "beheer leest logboek" on audit_log;
create policy "beheer leest logboek" on audit_log
  for select using (is_admin());

-- Verbruik: een lid ziet het eigen verbruik.
drop policy if exists "eigen verbruik" on ai_verbruik;
create policy "eigen verbruik" on ai_verbruik
  for select using (profile_id = auth.uid() or is_admin());

do $$
declare t text;
begin
  foreach t in array array['kompas_faq','kompas_stappen','paginas','ai_startsuggesties','feature_flags']
  loop
    execute format('drop policy if exists "beheer schrijft" on %I', t);
    execute format($f$
      create policy "beheer schrijft" on %I
        for all using (is_admin()) with check (is_admin())
    $f$, t);
  end loop;
end $$;
